const ON_ANIMATION_ENTER = 'event/ON_ANIMATION_START';
const ON_ANIMATION_EXIT = 'event/ON_ANIMATION_EXIT';
const ON_IDLE_SET = 'event/ON_IDLE_SET';
export {
  ON_ANIMATION_ENTER,
  ON_ANIMATION_EXIT,
  ON_IDLE_SET,
};
